### ISSUE TITLE
Ticket transfer in My Area

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#142]
Ticket transfers should be done from the Orders & Tickets section in My Area. Let's come up with what you should be able to do that makes sense.

- [x] The User has an overview of its Orders
- [x] The User must be able to see which Tickets were part of that Order, by clicking on the ( i ) button
- [ ] Order Details dialog should contain everything there is to know about that Order, and the Tickets that it included. This means current owner, transfers made (what more?)
- [x] It should list all Tickets the User currently _owns_
- [x] It should not list Tickets that have been transferred, that belongs in the Order details dialog
- [x] For each Ticket that the User owns, there should be a button to transfer that Ticket. Should this be based on username or email?
- [ ] If a transfer is sent, the icon should change to reflect the open transfer (a button to a Transfer details dialog?)
- [ ] The User needs a way to cancel the transfer. (from the Transfer details dialog?)
- [ ] Initiating a Transfer should state some terms, like CH-member and Pickup Service validity

Open questions:

1. Should the User be able to transfer _all_ of his Tickets, or should one remain locked?

**Comment by martijn9612** [comment]
I think it is better to let the transfer recipient accept the terms and conditions, not the sender of the ticket.
