### ISSUE TITLE
[My Area] Team creation, invites and mangement

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-frontend#177]
From My Area, you should be able to create a team and invite people to it

- [x] Create new Team (when you have a Ticket)
- [x] Invite Member to your Team as Captain
- [x] View open invites of a Team as Captain
- [x] Cancel invites of a Team as Captain
- [x] Remove members from your team as Captain

- [x] View personal invites
- [x] Accept personal invites
- [x] Decline personal invites
- [x] Remove yourself from a Team

**Comment by skamoen** [comment]
- [ ] Specify error when User doesn't have a Ticket but wants to do Team related things.
