### ISSUE TITLE
Rework client architecture to be compatible with polymer-build

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#283]
The current client architecture is incompatible with Polymer build. To be able to generate a PRPL-ready application, several changes are required:
- [ ] Rework `lancie-content` to allow lazy-loading of pages for faster first-paint
  - Adopt `iron-lazy-pages` to lazy-load pages
  - Check all imports to be correctly resolved
- [ ] Adopt a service-worker for faster cache results for static files (I should have a compatible one lying around somewhere)
- [x] Move files in `app/` to `src/` or `/`. All files should be served from `/` instead of `app/`, which means that files like `index.html` and `manifest.json` need to be in root. However, all other elements can remain in `src/` (which is a simple remain to be consistent with all other frontend projects)
- [x] Replace `page.js` with `app-route`

This is all based on https://github.com/PolymerElements/generator-polymer-init-custom-build and similar efforts I already did on other projects.

**Comment by TimvdLippe** [comment]
We will also need to adopt app-route to be able to efficiently load data in sub-routes.

**Comment by TimvdLippe** [comment]
A PR is ready for the second point at #285

**Comment by martijnjanssen** [comment]
The third part is done right now at #290

**Comment by martijnjanssen** [comment]
How relevant is this issue: #225 ? Looks almost identical to me, am I missing something?

**Comment by skamoen** [comment]
It's the same thing.

**Comment by TimvdLippe** [comment]
Only todo is SW, but we can do that later. Main architecture has been updated so the new LANcie can work on features :tada:
