### ISSUE TITLE
Action checklist

### ISSUE THREAD

**Issue by FrancisBehnen** [AreaFiftyLAN/lancie-frontend#358]
This is a (not yet complete) list of all actions a user can do on the front-end. @skamoen did you mean a complete front-end checklist or just a ticket flow checklist?

### Assuming user is at `/tickets`
- [ ]  Add ticket to basket
- [ ]  Add five tickets to basket
- [ ]  Unable to add sixth ticket to basket
- [ ]  Add ticket with option in basket
- [ ]  Remove ticket from basket
- [ ]  Remove ticket from basket when multiple tickets in basket (be sure that really the ticket you removed is actually the one that disappeared ;-)
- [ ]  Refresh at anytime while order stays 
- [ ]  Get tickets after payment
- [ ]  Don't get tickets if not paid
- [ ]  Don't get tickets if timed-out

**Comment by TimvdLippe** [comment]
We should really look into automating this process with acceptance tests, see #322

**Comment by FrancisBehnen** [comment]
Yea of course, maybe this list can become part of that epic as the list of all things we should write a test for?
